package com.ph.prioritychecker.model

// ─── Language Enum ────────────────────────────────────────────────────────────

enum class Language(val code: String, val nativeName: String) {
    GERMAN("de", "Deutsch"),
    ENGLISH("en", "English")
}

// ─── Localized Strings ────────────────────────────────────────────────────────

data class AppStrings(
    val activePlayer: String,
    val nonActivePlayer: String,
    val activePlayerShort: String,
    val nonActivePlayerShort: String,
    val nobody: String,
    val priority: String,
    val hasPriority: String,
    val passedLabel: String,
    val stillWaiting: String,
    val priorityFlow: String,
    val passPriority: String,
    val stepEnd: String,
    val resolveStack: String,
    val addToStack: String,
    val nextStep: String,
    val nextTurn: String,
    val confirm: String,
    val cancel: String,
    val save: String,
    val close: String,
    val mandatoryAction: String,
    val mandatoryNoStack: String,
    val untapDone: String,
    val drawDone: String,
    val attackersDeclared: String,
    val blockersDeclared: String,
    val firstStrikeDamageDone: String,
    val combatDamageDone: String,
    val cleanupDone: String,
    val noMandatoryNextStep: String,
    val stackTitle: String,
    val stackEmpty: String,
    val resolvesNext: String,
    val topResolvesFirst: String,
    val removedFromStack: String,
    val typeInstant: String,
    val typeSorcery: String,
    val typeCreature: String,
    val typeArtifact: String,
    val typeEnchantment: String,
    val typePlaneswalker: String,
    val typeBattle: String,
    val typeActivatedAbility: String,
    val typeTriggeredAbility: String,
    val typeLand: String,
    val typeOther: String,
    val whatCanBePlayed: String,
    val instantSpeed: String,
    val sorcerySpeed: String,
    val sorcerySpeedBlocked: String,
    val sorcerySpeedNA: String,
    val landPlay: String,
    val landPlayDetail: String,
    val nothingPlayable: String,
    val stackMustBeEmpty: String,
    val onlyInMainPhase: String,
    val settingsTitle: String,
    val playerOneName: String,
    val playerTwoName: String,
    val languageSetting: String,
    val firstStrikeSetting: String,
    val firstStrikeDetail: String,
    val resetGame: String,
    val referenceTitle: String,
    val corePriorityRules: String,
    val allStepsTitle: String,
    val noMandatoryLabel: String,
    val conditionalLabel: String,
    val afterMandatoryLabel: String,
    val firstPriorityLabel: String,
    val instantLabel: String,
    val sorceryLabel: String,
    val searchCard: String,
    val searchPlaceholder: String,
    val searching: String,
    val noResults: String,
    val searchError: String,
    val tapToSelect: String,
    val longPressHint: String,
    val cardPreview: String,
    val manualEntrySection: String,
    val effectDescription: String,
    val effectType: String,
    val addButton: String,
    val secondPassWarningEmpty: String,
    val secondPassWarningStack: String,
    val turnEnd: String,
    val roundLabel: String,
    val optional: String,
    val specialRulesTitle: String,
    val controlledBy: String,
    val triggerLabel: String,
)

// ─── German ───────────────────────────────────────────────────────────────────

fun germanStrings() = AppStrings(
    activePlayer = "Aktiver Spieler",
    nonActivePlayer = "Passiver Spieler",
    activePlayerShort = "AS",
    nonActivePlayerShort = "PS",
    nobody = "Niemand",
    priority = "PRIORITÄT",
    hasPriority = "HAT PRIORITÄT",
    passedLabel = "Gepasst",
    stillWaiting = "wartet noch",
    priorityFlow = "Prioritätsfluss",
    passPriority = "→ Prio abgeben",
    stepEnd = "⏭ Schritt enden",
    resolveStack = "⏭ Auflösen",
    addToStack = "Auf Stack",
    nextStep = "▶ Weiter",
    nextTurn = "🔄 Nächster Zug",
    confirm = "Bestätigen",
    cancel = "Abbrechen",
    save = "Speichern",
    close = "Schließen",
    mandatoryAction = "Pflichtaktion",
    mandatoryNoStack = "Pflichtaktion (kein Stack)",
    untapDone = "Enttappen abgeschlossen",
    drawDone = "Karte gezogen → Priorität vergeben",
    attackersDeclared = "Angreifer erklärt",
    blockersDeclared = "Blocker erklärt + Reihenfolge",
    firstStrikeDamageDone = "Erstangriff-Schaden zugeteilt",
    combatDamageDone = "Kampfschaden zugeteilt",
    cleanupDone = "Aufräumen abgeschlossen",
    noMandatoryNextStep = "→ Nächster Schritt (keine Priorität)",
    stackTitle = "STACK",
    stackEmpty = "Stack ist leer.",
    resolvesNext = "← löst als Nächstes auf",
    topResolvesFirst = "↑ oben löst zuerst auf",
    removedFromStack = "Effekt manuell vom Stack entfernt.",
    typeInstant = "Spontanzauber",
    typeSorcery = "Hexerei",
    typeCreature = "Kreatur",
    typeArtifact = "Artefakt",
    typeEnchantment = "Verzauberung",
    typePlaneswalker = "Planeswalker",
    typeBattle = "Schlacht",
    typeActivatedAbility = "Aktivierte Fähigkeit",
    typeTriggeredAbility = "Trigger-Effekt",
    typeLand = "Land",
    typeOther = "Sonstiges",
    whatCanBePlayed = "WAS KANN GESPIELT WERDEN?",
    instantSpeed = "Instant-Geschwindigkeit",
    sorcerySpeed = "Hexerei-Geschwindigkeit (Stack leer!)",
    sorcerySpeedBlocked = "Hexerei-Geschwindigkeit gesperrt",
    sorcerySpeedNA = "Hexerei-Geschwindigkeit N/A",
    landPlay = "Land spielen",
    landPlayDetail = "Max. 1 Land pro Zug (keine Stack-Aktion)",
    nothingPlayable = "Keine Karten spielbar.",
    stackMustBeEmpty = "Stack muss leer sein",
    onlyInMainPhase = "Nur in Hauptphasen möglich",
    settingsTitle = "Einstellungen",
    playerOneName = "⚔️ Aktiver Spieler",
    playerTwoName = "🛡️ Passiver Spieler",
    languageSetting = "Sprache / Language",
    firstStrikeSetting = "Erstangriff-Schadensschritt",
    firstStrikeDetail = "Einblenden wenn First/Double Strike",
    resetGame = "🔄 Spiel zurücksetzen",
    referenceTitle = "Prioritäts-Übersicht",
    corePriorityRules = "Kern-Prioritätsregeln (CR 117)",
    allStepsTitle = "Alle Schritte",
    noMandatoryLabel = "❌ Keine Priorität",
    conditionalLabel = "⚠️ Bedingt (bei Trigger)",
    afterMandatoryLabel = "⚡ Nach Pflichtaktion → AS",
    firstPriorityLabel = "✅ AS erhält Priorität zuerst",
    instantLabel = "⚡ Instant",
    sorceryLabel = "📜 Sorcery (AS)",
    searchCard = "Karte suchen (Scryfall)",
    searchPlaceholder = "Kartenname auf Deutsch oder Englisch…",
    searching = "Suche läuft…",
    noResults = "Keine Karten gefunden.",
    searchError = "Netzwerkfehler – manuelle Eingabe nutzen.",
    tapToSelect = "Tippen zum Auswählen",
    longPressHint = "Lang drücken für Kartenvorschau",
    cardPreview = "Kartenvorschau",
    manualEntrySection = "Oder manuell eingeben:",
    effectDescription = "Beschreibung",
    effectType = "Typ",
    addButton = "Auf Stack legen",
    secondPassWarningEmpty = "Zweiter Pass → Schritt endet (Stack leer)",
    secondPassWarningStack = "Zweiter Pass → Oberstes Element wird aufgelöst",
    turnEnd = "Zugabende. Drücke 'Nächster Zug' um fortzufahren.",
    roundLabel = "Runde",
    optional = "OPTIONAL",
    specialRulesTitle = "Spezialregeln & Hinweise",
    controlledBy = "kontrolliert von",
    triggerLabel = "Trigger",
)

// ─── English ──────────────────────────────────────────────────────────────────

fun englishStrings() = AppStrings(
    activePlayer = "Active Player",
    nonActivePlayer = "Non-Active Player",
    activePlayerShort = "AP",
    nonActivePlayerShort = "NAP",
    nobody = "Nobody",
    priority = "PRIORITY",
    hasPriority = "HAS PRIORITY",
    passedLabel = "Passed",
    stillWaiting = "still waiting",
    priorityFlow = "Priority Flow",
    passPriority = "→ Pass Priority",
    stepEnd = "⏭ End Step",
    resolveStack = "⏭ Resolve",
    addToStack = "Add Stack",
    nextStep = "▶ Next",
    nextTurn = "🔄 Next Turn",
    confirm = "Confirm",
    cancel = "Cancel",
    save = "Save",
    close = "Close",
    mandatoryAction = "Mandatory Action",
    mandatoryNoStack = "Mandatory Action (no stack)",
    untapDone = "Untap completed",
    drawDone = "Card drawn → Priority granted",
    attackersDeclared = "Attackers declared",
    blockersDeclared = "Blockers declared + damage order",
    firstStrikeDamageDone = "First strike damage dealt",
    combatDamageDone = "Combat damage dealt",
    cleanupDone = "Cleanup completed",
    noMandatoryNextStep = "→ Next Step (no priority)",
    stackTitle = "STACK",
    stackEmpty = "Stack is empty.",
    resolvesNext = "← resolves next",
    topResolvesFirst = "↑ top resolves first",
    removedFromStack = "Effect manually removed from stack.",
    typeInstant = "Instant",
    typeSorcery = "Sorcery",
    typeCreature = "Creature",
    typeArtifact = "Artifact",
    typeEnchantment = "Enchantment",
    typePlaneswalker = "Planeswalker",
    typeBattle = "Battle",
    typeActivatedAbility = "Activated Ability",
    typeTriggeredAbility = "Triggered Ability",
    typeLand = "Land",
    typeOther = "Other",
    whatCanBePlayed = "WHAT CAN BE PLAYED?",
    instantSpeed = "Instant Speed",
    sorcerySpeed = "Sorcery Speed (stack empty!)",
    sorcerySpeedBlocked = "Sorcery Speed blocked",
    sorcerySpeedNA = "Sorcery Speed N/A",
    landPlay = "Play a Land",
    landPlayDetail = "Max. 1 land per turn (not a stack action)",
    nothingPlayable = "No cards can be played.",
    stackMustBeEmpty = "Stack must be empty",
    onlyInMainPhase = "Only possible in main phases",
    settingsTitle = "Settings",
    playerOneName = "⚔️ Active Player",
    playerTwoName = "🛡️ Non-Active Player",
    languageSetting = "Language / Sprache",
    firstStrikeSetting = "First Strike Damage Step",
    firstStrikeDetail = "Show when First/Double Strike involved",
    resetGame = "🔄 Reset Game",
    referenceTitle = "Priority Reference",
    corePriorityRules = "Core Priority Rules (CR 117)",
    allStepsTitle = "All Steps",
    noMandatoryLabel = "❌ No Priority",
    conditionalLabel = "⚠️ Conditional (on trigger)",
    afterMandatoryLabel = "⚡ After mandatory → AP",
    firstPriorityLabel = "✅ AP gets priority first",
    instantLabel = "⚡ Instant",
    sorceryLabel = "📜 Sorcery (AP)",
    searchCard = "Search Card (Scryfall)",
    searchPlaceholder = "Card name in German or English…",
    searching = "Searching…",
    noResults = "No cards found.",
    searchError = "Network error – use manual entry.",
    tapToSelect = "Tap to select",
    longPressHint = "Long press for card preview",
    cardPreview = "Card Preview",
    manualEntrySection = "Or enter manually:",
    effectDescription = "Description",
    effectType = "Type",
    addButton = "Add to Stack",
    secondPassWarningEmpty = "Second pass → Step ends (stack empty)",
    secondPassWarningStack = "Second pass → Top of stack resolves",
    turnEnd = "Turn end reached. Press 'Next Turn' to continue.",
    roundLabel = "Round",
    optional = "OPTIONAL",
    specialRulesTitle = "Special Rules & Notes",
    controlledBy = "controlled by",
    triggerLabel = "Trigger",
)
